name: benecol_flutter
description: A new Flutter project.
publish_to: 'none' 
version: 3.1.4+21

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.4+1
  firebase_messaging: ^11.2.5
  firebase_core: 1.11.0
  firebase_core_platform_interface: 4.5.1

#  firebase_messaging: ^14.1.4
#  firebase_core: 2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.0
  flutter_easyloading: ^3.0.0
  http: ^0.13.3
  flutter_local_notifications: ^8.1.1+1
  permission_handler: ^8.1.4+2
  flutter_html: ^2.2.1
  intl: ^0.17.0
  shared_preferences: ^2.0.7
  table_calendar: ^3.0.2
  location: ^4.4.0
  flutter_launcher_icons: "^0.9.2"
  geolocator: ^7.7.1
  google_maps_flutter: ^2.0.0
  cached_network_image: ^3.1.0
  url_launcher: ^6.0.10
  youtube_player_flutter: ^8.0.0
  jwt_decoder: ^2.0.1
  youtube_player_iframe: ^2.2.2
  package_info: ^2.0.2
  store_redirect: ^2.0.0
  flutter_math_fork: ^0.5.0
  dotted_border: any


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/splash/
    - assets/images/home/
    - assets/images/home/en/
    - assets/images/home/zh_Hant/
    - assets/images/share/
    - assets/images/login/
    - assets/images/myAccount/
    - assets/images/myAccount/14.jpg
    - assets/images/myAccount/15.jpg
    - assets/images/myAccount/16.jpg
    - assets/images/imageBanner/
    - assets/images/instruction/
    - assets/icons/
